name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  check-build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - name: Npm setup
        run: npm install

      - name: Build and check
        run: npm run build
